#pixi run pip install --no-deps --force-reinstall git+https://github.com/PaNOSC-ViNYL/McStasScript.git@custom_component_dir#egg=mcstasscript
[project]
authors = [{name = "Shervin Nourbakhsh", email = "shervin86@posteo.net"}]
dependencies = []
name = "instrument_database"
requires-python = ">= 3.11,<3.13"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
instrument_database = { path = ".", editable = true }
instrumentdatabaseapi = { path = "./instrumentDataBaseAPI"}



[tool.pixi.tasks]
deps_libpyvinyl = { cmd = [ "pip", "install", "--no-deps", "--force-reinstall", "git+https://github.com/PaNOSC-ViNYL/libpyvinyl.git@hash2#egg=libpyvinyl" ], description="Update libpyvinyl with custom branch" }
deps = { cmd = [ "pip", "install", "--no-deps", "--force-reinstall", "git+https://github.com/PaNOSC-ViNYL/McStasScript.git@custom_component_dir#egg=mcstasscript" ], description="Update mcstasscript with custom branch", depends-on=["deps_libpyvinyl"] }

[tool.pixi.dependencies]
mcstas = "3.6.5.*"
ipykernel = ">=7.2.0"
pytest = ">=9.0.2,<10"
pytest_check = ">=2.7.6,<3"
