[pytest]
#pythonpath = institutes/ILL/instruments/D11/HEAD/mcstas/ mcstas/ .
pythonpath = mcstas .
#testpaths = institutes/ILL/instruments/D11/HEAD/mcstas/
#testpaths = institutes/ILL/instruments/Panther/HEAD/mcstas/
testpaths = institutes/ILL/instruments/IN5/HEAD/mcstas/
python_files = test.py test_Panther.py test_IN5.py
addopts =  -v
# -s