/*******************************************************************************
*
* McStas, neutron ray-tracing package
*         Copyright 1997-2002, All rights reserved
*         Risoe National Laboratory, Roskilde, Denmark
*         Institut Laue Langevin, Grenoble, France
*
* Component: Cyl_TOF
*
* %I
* Written by:  Shervin Nourbakhsh
* Date: October 2023
* Origin: ILL
* Based on TOF_cyl_PSD_monitor by Kim Lefmann
*
* Cylindrical (2pi) PSD Time-of-flight monitor.
*
* %D
*
* %P
* INPUT PARAMETERS:
*
* radius: [m]           Cylinder radius
* yheight: [m]          Cylinder height
* nphi: [deg]           Number of angular bins
* ny: [1]               Number of bins on the vertical axis
* nt: [1]               Number of time bins
* phimin: [deg]         Beginning of the detector
* phimax: [deg]         End of the detector
* tmin: [s]             Beginning of time window
* tmax: [s]             End of time window
* filename: [string]    Name of file in which to store the detector image
* restore_neutron: [1]  If set, the monitor does not influence the neutron state
* nowritefile: [1]      If set, monitor will skip writing to disk
* tshift: [s]           Shift the time of the neutron, effectively repositioning the 0. Done before defining the time bin.
*
* OUTPUT PARAMETERS:
*
* TOF_N: []             Array of neutron counts
* TOF_p: []             Array of neutron weight counts
* TOF_p2: []            Array of second moments
*
* %E
*******************************************************************************/

DEFINE COMPONENT Cyl_TOF
DEFINITION PARAMETERS ()
  SETTING PARAMETERS (nt=128,  ny=1, string filename=0, int nowritefile=0, radius=1, yheight=2, phimin=0, tmin=0, tmax=1, restore_neutron=0, tshift=0, nphi_groups=1, nphi_pergroup=1, phi_groupgap=0., phi_binwidth=1.)
OUTPUT PARAMETERS ()
/* Neutron parameters: (x,y,z,vx,vy,vz,t,sx,sy,sz,p) */

DECLARE
%{
  #include <math.h>
  DArray3d TOF_N;
  DArray3d TOF_p;
  DArray3d TOF_p2;
  double ybinwidth;
  double tbinwidth;
  int nphi;
  double phimax;
%}

INITIALIZE
%{
  int iphi, iy, it;
  nphi = nphi_groups*nphi_pergroup;
  TOF_N  = create_darr3d(nphi, ny, nt);
  TOF_p  = create_darr3d(nphi, ny, nt);
  TOF_p2 = create_darr3d(nphi, ny, nt);

  /* initialize the counters */
  for (iphi=0; iphi<nphi; iphi++) {
    for (iy=0; iy<ny; iy++)
      for(it=0; it<nt; it++){
	{
	  TOF_N[iphi][iy][it] = 0;
	  TOF_p[iphi][iy][it] = 0;
	  TOF_p2[iphi][iy][it] = 0;
	}
      }
  }

  //if(tmax<tmin) ERROR
  phimax = phimin + nphi_groups*phi_binwidth*nphi_pergroup + (nphi_groups-1)*phi_groupgap;
  printf("phimax = %.2f\n", phimax);
  ybinwidth   = (yheight)      /(double)ny;
  tbinwidth   = (tmax-tmin)    /(double)nt;
  // Use instance name for monitor output if no input was given
  if (!strcmp(filename,"\0")) sprintf(filename,"Cyl_TOF");
  printf("Cyl_TOF file: %s\n", filename);
%}

TRACE
%{
  int iy,it;
  double cyl_t0,cyl_t1,tshifted,phi,yh;
  
  if(!cylinder_intersect(&cyl_t0, &cyl_t1, x,y,z,vx,vy,vz, radius, yheight))
   /* No hit */
    ABSORB;
  if(cyl_t0>0)  /* Neutron hits cylinder from the outside */
    ABSORB;

  /* propagate the neutron to the cylinder surface */
  PROP_DT(cyl_t1);
  yh = yheight/2;
    
  if(y >= yh || y <= -yh)
    ABSORB;  /* Neutron hits cylinder ends; no detectors here */
  
  /* Calculate pixel */
  tshifted = t + tshift;
  phi=atan2(x,z)*RAD2DEG;

  
  if (phi >= phimin && phi <= phimax) {
    if ( tshifted >= tmin && tshifted <= tmax) {
      /* check if in gap between tube modules */
      double deltaphi=phi-phimin;
      double total_groupwidth =  nphi_pergroup*phi_binwidth+phi_groupgap;
      double igroup=0;
      deltaphi= modf(deltaphi/total_groupwidth,&igroup);
      if(deltaphi> 1 - phi_groupgap/total_groupwidth)	ABSORB;
      
      int iphi = floor((deltaphi*total_groupwidth)/phi_binwidth +igroup*nphi_pergroup);
      if(iphi>nphi-1){
	printf("iphi = %d, phi = %f\n", iphi, phi);
	ABSORB;
      }
      iy   = floor( (y+yh)/ybinwidth );
      if (iy>=ny) ABSORB;
      it   = floor( (tshifted-tmin)/tbinwidth );
      double p2 = p*p;
      /* printf("iphi = %d\niy = %d\nit = %d\nt = %.2e\ntmin = %.2e\ny = %.2e\nyh = %.2f", iphi, iy, it, tshifted, tmin, y, yh); */

      /* ATTENTION! the pixel at the lower left side has high phi because x is positive toward left
       * but we want that pixel to be the origin of the axis in the plot, so (0,0) with x positive toward the right and y positive going up
       * This requires inverting the bins in phi.
       */
      //iphi=nphi-iphi;


#pragma acc atomic
      TOF_N[iphi][iy][it] = TOF_N[iphi][iy][it]+1;
      
#pragma acc atomic
      TOF_p[iphi][iy][it] = TOF_p[iphi][iy][it]+p;
      
#pragma acc atomic
      TOF_p2[iphi][iy][it] = TOF_p2[iphi][iy][it]+p2;
    }//else{printf("Out of t: %f\t%f\n", tshifted, t);}
  }//else{printf("Out of phi: %f\n", phi);}

  
  if (restore_neutron) {
    RESTORE_NEUTRON(INDEX_CURRENT_COMP, x, y, z, vx, vy, vz, t, sx, sy, sz, p);
  }
%}

SAVE
%{
if (!nowritefile) {
  int iphi;
  for(iphi=0; iphi < nphi; iphi++){
    char ff[256];
    char tt[256];
    sprintf(ff, "%s_%03i",filename,iphi);
    sprintf(tt, "PSD TOF monitor: tube %i ",iphi);
    DETECTOR_OUT_2D(
      tt,
      "Y position [m]",
      "time [s]",
      -yheight*0.5, yheight*0.5, tmin, tmax,
      ny, nt,
      &TOF_N[iphi][0][0],&TOF_p[iphi][0][0],&TOF_p2[iphi][0][0],
      ff);
  }
}
%}

FINALLY
%{
  destroy_darr3d(TOF_N);
  destroy_darr3d(TOF_p);
  destroy_darr3d(TOF_p2);
%}

MCDISPLAY
%{
  magnify("y");
  circle("xz", 0,0,0,radius);
%}

END
